/* 50 ready-to-edit KADA email templates. Each returns a single inline-styled  */
/* <div> — email-safe (no <style>, no external CSS) — using the brand palette  */
/* (emerald #0b3d2e, gold #c9a227, cream #f6f3ea). {{name}} = recipient name.  */

const E = '#0b3d2e'
const G = '#c9a227'
const C = '#f6f3ea'
const IVORY = '#fffdf8'
const INK = '#232323'
const MUTED = '#767066'
const SERIF = "Georgia,'Times New Roman',serif"
const SANS = "Arial,Helvetica,sans-serif"
const SITE = 'https://kingsarkdance.com'

const shell = (inner, accent = E) => `<div style="background:${C};padding:32px 16px;font-family:${SANS};color:${INK};line-height:1.6"><div style="max-width:560px;margin:0 auto;background:${IVORY};border:1px solid #e4ddc9;border-radius:14px;overflow:hidden"><div style="height:6px;background:linear-gradient(90deg,${accent},${G})"></div><div style="padding:28px 28px 8px">${inner}</div><div style="padding:18px 28px 26px;font-size:12px;color:${MUTED};border-top:1px solid #eee7d2;margin-top:20px">King's Ark Dance Academy · Birmingham · <a href="${SITE}" style="color:${E}">kingsarkdance.com</a><br>You're receiving this because you're part of the KADA community.</div></div></div>`
const h1 = (text, color = E) => `<h1 style="font-family:${SERIF};font-size:26px;font-weight:500;color:${color};margin:0 0 14px;line-height:1.25">${text}</h1>`
const p = (text) => `<p style="margin:0 0 14px;font-size:15px">${text}</p>`
const cta = (label, url = SITE) => `<p style="margin:20px 0 6px"><a href="${url}" style="background:${E};color:${IVORY};padding:12px 22px;border-radius:8px;text-decoration:none;font-weight:700;display:inline-block;font-size:14px">${label} →</a></p>`
const ctaGold = (label, url = SITE) => `<p style="margin:20px 0 6px"><a href="${url}" style="background:${G};color:${E};padding:12px 22px;border-radius:8px;text-decoration:none;font-weight:700;display:inline-block;font-size:14px">${label} →</a></p>`
const eyebrow = (text) => `<p style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:${G};font-weight:700;margin:0 0 8px">${text}</p>`
const sig = (name = 'Steven', role = 'Founder, KADA') => `<p style="margin:18px 0 0;font-size:14px">With love and purpose,<br><strong>${name}</strong><br><span style="color:${MUTED};font-size:13px">${role}</span></p>`
const divider = `<hr style="border:0;border-top:1px solid #eee7d2;margin:18px 0">`
const chip = (text) => `<span style="background:${C};border:1px solid #e4ddc9;border-radius:20px;padding:4px 12px;font-size:12px;display:inline-block;margin:0 6px 6px 0">${text}</span>`
const quote = (text, who) => `<div style="border-left:3px solid ${G};padding:4px 0 4px 16px;margin:16px 0;font-style:italic;color:${INK};font-size:15px">“${text}”<div style="font-style:normal;font-size:12px;color:${MUTED};margin-top:6px">— ${who}</div></div>`

const T = (category, name, subject, body) => ({ category, name, subject, body })

export const TEMPLATES = [
  // ── Announcements ────────────────────────────────────────────────
  T('Announcements', 'New term enrolment', 'A new term of dance begins soon 💛', shell(`${eyebrow('Enrolment open')}${h1('A brand new term is almost here, {{name}}.')}${p('Saturday classes return soon at King\'s Ark Dance Academy — fresh routines, new music, and the same joyful, faith-rooted community your child loves.')}${p('Places go quickly, so secure yours early.')}${cta('Book a Saturday class')}${sig()}`)),
  T('Announcements', 'New workshop launch', 'We\'re bringing Afrobeats to more schools', shell(`${eyebrow('For schools')}${h1('Bring your school to life through Afrobeats.')}${p('Hi {{name}} — our high-energy, fully interactive workshops are now open for booking: enrichment days, Culture Days and Black History Month.')}${p('No dance experience needed — only enthusiasm.')}${ctaGold('Get a quote for your school')}${sig()}`)),
  T('Announcements', 'New class added', 'We\'ve added a new class to the schedule', shell(`${eyebrow('New class')}${h1('Good news — there\'s a new class on the schedule.')}${p('{{name}}, we\'ve added another session so more children can dance with us each week.')}${p('Check the timetable and grab a place before it fills.')}${cta('See the schedule')}${sig()}`)),
  T('Announcements', 'Big announcement', 'Something exciting is coming to KADA', shell(`${eyebrow('Announcement')}${h1('We\'ve been working on something special.')}${p('Hi {{name}} — we can\'t wait to share what\'s next for King\'s Ark Dance Academy. Keep an eye on your inbox and our Instagram.')}${cta('Follow the journey', 'https://www.instagram.com/kingsarkdance')}${sig()}`)),
  T('Announcements', 'New partner school', 'Welcome to our newest partner school', shell(`${eyebrow('Growing community')}${h1('Our KADA family just got bigger.')}${p('{{name}}, we\'re delighted to welcome a new partner school into the KADA community this term.')}${p('Every new school means more children building confidence through Gospel Afrobeats.')}${sig()}`)),
  T('Announcements', 'New instructor joined', 'Meet the newest member of our team', shell(`${eyebrow('Team news')}${h1('Please welcome our newest instructor.')}${p('Hi {{name}} — our team is growing, and we\'re so excited to introduce the newest instructor joining the KADA family.')}${p('Every instructor is DBS-checked, brilliant with children, and passionate about building confidence through dance.')}${sig()}`)),
  T('Announcements', 'Website update', 'Our website just got better', shell(`${eyebrow('What\'s new')}${h1('Booking with KADA just got easier.')}${p('{{name}}, we\'ve refreshed our website — simpler class booking, clearer workshop info, and a brand new parent portal.')}${cta('Take a look')}${sig()}`)),
  T('Announcements', 'General news update', 'A little update from KADA', shell(`${eyebrow('News')}${h1('Here\'s what\'s been happening at KADA.')}${p('Hi {{name}} — a quick note to keep you in the loop with everything going on at King\'s Ark Dance Academy this month.')}${p('[Add your news here — a few sentences about what\'s new.]')}${cta('Visit the website')}${sig()}`)),
  T('Announcements', 'New video released', 'Watch our latest video', shell(`${eyebrow('Watch now')}${h1('Real stories, real confidence.')}${p('{{name}}, we\'ve just shared a new video — real children, real growth, real joy. It\'s the heart of what we do.')}${cta('Watch now')}${sig()}`)),
  T('Announcements', 'Milestone reached', 'We just hit a big milestone 🎉', shell(`${eyebrow('Milestone')}${h1('We couldn\'t have done this without you.')}${p('{{name}}, thanks to families and schools like yours, KADA has just reached an incredible milestone — over 1,000 children empowered and counting.')}${p('Every single child matters. Thank you for being part of the movement.')}${sig()}`)),

  // ── Workshops / schools ──────────────────────────────────────────
  T('Workshops', 'Black History Month pitch', 'Black History Month, done differently', shell(`${eyebrow('October · Black History Month')}${h1('Bring BHM to life through Gospel Afrobeats.')}${p('Hi {{name}} — Black History Month is our busiest time of year. Our workshops celebrate heritage, joy and culture in a way children genuinely remember.')}${p('Dates fill fast — schools usually book 6–8 weeks ahead.')}${ctaGold('Check availability')}${sig()}`)),
  T('Workshops', 'Culture Day pitch', 'Make your Culture Day unforgettable', shell(`${eyebrow('Culture Day')}${h1('One hour. A whole school buzzing.')}${p('{{name}}, a KADA Culture Day workshop gets every child moving, laughing and learning — no experience needed.')}${p('We handle everything: music, structure, energy. Your staff just enjoy it.')}${ctaGold('Plan our Culture Day')}${sig()}`)),
  T('Workshops', 'Enrichment day pitch', 'An enrichment day they\'ll talk about for weeks', shell(`${eyebrow('Enrichment days')}${h1('Give your pupils a day that builds real confidence.')}${p('Hi {{name}} — our full-day enrichment workshops blend dance, teamwork and character-building, rooted in Gospel Afrobeats.')}${ctaGold('Get a quote')}${sig()}`)),
  T('Workshops', 'Half-day option', 'A half-day workshop, full of energy', shell(`${eyebrow('Half-day workshops')}${h1('Big impact, half the day.')}${p('{{name}}, short on time? Our half-day workshop packs the full KADA experience into a morning or afternoon.')}${p(`${chip('Up to 3 classes')}${chip('All ages')}${chip('No experience needed')}`)}${ctaGold('Book a half-day')}${sig()}`)),
  T('Workshops', 'Follow-up after enquiry', 'Following up on your workshop enquiry', shell(`${eyebrow('Following up')}${h1('Still thinking about a workshop, {{name}}?')}${p('You reached out about bringing KADA to your school — just checking in to see if you\'d like us to hold a date or answer any questions.')}${p('No pressure at all. We\'re here when you\'re ready.')}${cta('Reply to us', 'mailto:bookings@kingsarkdance.com')}${sig()}`)),
  T('Workshops', 'Thank you after workshop', 'Thank you for having us!', shell(`${eyebrow('Thank you')}${h1('What a day we had together!')}${p('{{name}}, thank you for welcoming KADA into your school. The energy, the courage, the joy — your pupils were brilliant.')}${p('We\'d love to come back. And if you know another school who\'d benefit, an introduction means the world.')}${cta('Book a return visit')}${sig()}`)),
  T('Workshops', 'Rebooking reminder', 'Shall we get next term in the diary?', shell(`${eyebrow('Plan ahead')}${h1('Let\'s get next term\'s workshop booked in.')}${p('Hi {{name}} — our diary for next term is filling up. As a school we\'ve worked with before, you get first choice of dates.')}${ctaGold('Reserve a date')}${sig()}`)),
  T('Workshops', 'Assembly + workshop combo', 'Start the day with a whole-school assembly', shell(`${eyebrow('Assembly + workshop')}${h1('Open with an assembly, then dance all day.')}${p('{{name}}, our most popular format: a whole-school assembly to set the tone, then class-by-class workshops through the day.')}${ctaGold('See the format')}${sig()}`)),
  T('Workshops', 'Staff wellbeing session', 'A dance session your staff will love', shell(`${eyebrow('Staff wellbeing')}${h1('Not just for pupils — your staff deserve this.')}${p('Hi {{name}} — we run uplifting, laughter-filled Afrobeats sessions for school staff too. Perfect for INSET days and wellbeing weeks.')}${cta('Ask about staff sessions')}${sig()}`)),
  T('Workshops', 'End-of-year celebration', 'End the school year on a high', shell(`${eyebrow('End of year')}${h1('Finish the year with joy, music and movement.')}${p('{{name}}, celebrate your pupils\' hard work with a KADA end-of-year workshop — the perfect send-off into summer.')}${ctaGold('Book for July')}${sig()}`)),

  // ── Classes / parents ────────────────────────────────────────────
  T('Classes', 'Welcome new parent', 'Welcome to the KADA family 💛', shell(`${eyebrow('Welcome')}${h1('{{name}}, welcome to King\'s Ark Dance Academy.')}${p('We\'re so glad you\'re here. Your child is about to build confidence, creativity and friendships — all through Gospel Afrobeats.')}${p('Your parent portal is where you\'ll book classes, see your children\'s details, and keep everything up to date.')}${cta('Open the parent portal')}${sig()}`)),
  T('Classes', 'Class reminder', 'Class is this Saturday — see you there!', shell(`${eyebrow('Reminder')}${h1('See you on Saturday, {{name}}!')}${p('A friendly reminder that class is on this Saturday. Bring water, comfy clothes, and that big energy we love.')}${p('Running late or can\'t make it? Just let us know.')}${sig()}`)),
  T('Classes', 'Membership renewal', 'Your KADA membership — a quick check-in', shell(`${eyebrow('Membership')}${h1('Keeping your child\'s place, {{name}}.')}${p('Your monthly membership keeps your child\'s place in class every Saturday, and helps us plan brilliant sessions.')}${p('Need to update payment details or pause? Your parent portal has it all.')}${cta('Manage my membership')}${sig()}`)),
  T('Classes', 'Bring a friend day', 'Bring a friend for free this Saturday', shell(`${eyebrow('Bring a friend')}${h1('Double the joy — bring a friend for free.')}${p('{{name}}, this Saturday your child can bring a friend to class at no cost. The more, the merrier!')}${cta('Reserve the free place')}${sig()}`)),
  T('Classes', 'Progress update', 'Look how far your child has come', shell(`${eyebrow('Progress')}${h1('{{name}}, your child is growing beautifully.')}${p('We see it every week — more confidence, sharper moves, bigger smiles. Dance is the vehicle; confidence is what we\'re building.')}${p('[Add a personal note about their child here.]')}${sig()}`)),
  T('Classes', 'Missed you last week', 'We missed you on Saturday', shell(`${eyebrow('We missed you')}${h1('Everything okay, {{name}}?')}${p('We noticed your child wasn\'t in class this Saturday and just wanted to check in. No worries at all — we\'ll see you next week.')}${p('If anything\'s changed or you need to pause, just reply to this email.')}${sig()}`)),
  T('Classes', 'New term dates', 'Term dates for your diary', shell(`${eyebrow('Term dates')}${h1('Here are the dates for the new term.')}${p('Hi {{name}} — the new term\'s class dates are confirmed. Pop them in your calendar so you never miss a Saturday.')}${p('[Add term dates here.]')}${cta('View the schedule')}${sig()}`)),
  T('Classes', 'Day pass promo', 'Try a class with a £10 day pass', shell(`${eyebrow('Try it out')}${h1('Not ready for membership? Try a day pass.')}${p('{{name}}, our £10 day pass lets your child experience a full Saturday class — no commitment, just joy.')}${ctaGold('Get a day pass')}${sig()}`)),
  T('Classes', 'Uniform / what to wear', 'What to wear to class', shell(`${eyebrow('Good to know')}${h1('What should your child wear to class?')}${p('Hi {{name}} — comfy clothes they can move in, trainers, and a water bottle. That\'s it. No special kit needed.')}${sig()}`)),
  T('Classes', 'Payment failed notice', 'A quick note about your payment', shell(`${eyebrow('Payment')}${h1('{{name}}, your last payment didn\'t go through.')}${p('This happens more often than you\'d think — usually an expired card. Update your details in the parent portal and your child\'s place stays secure.')}${cta('Update payment details')}${sig()}`)),

  // ── Events ───────────────────────────────────────────────────────
  T('Events', 'Event announcement', 'You\'re invited: our next KADA event', shell(`${eyebrow('You\'re invited')}${h1('Save the date, {{name}} — something special is coming.')}${p('We\'d love you and your family at our next event. Expect joy, music, movement and the KADA community at its best.')}${p('[Add event name, date and venue here.]')}${ctaGold('Get tickets')}${sig()}`)),
  T('Events', 'Early bird tickets', 'Early-bird tickets now open', shell(`${eyebrow('Early bird')}${h1('Get in early, {{name}} — and save.')}${p('Early-bird tickets for our next event are live now, at a special price. When they\'re gone, they\'re gone.')}${ctaGold('Get early-bird tickets')}${sig()}`)),
  T('Events', 'Last tickets warning', 'Last few tickets remaining', shell(`${eyebrow('Almost sold out')}${h1('This is nearly full, {{name}}.')}${p('If you\'ve been meaning to grab tickets, now\'s the time — we\'re down to the last few.')}${cta('Get tickets before they\'re gone')}${sig()}`)),
  T('Events', 'Event reminder (1 week)', 'One week to go!', shell(`${eyebrow('One week to go')}${h1('We can\'t wait to see you, {{name}}.')}${p('Your event is just a week away. Here\'s everything you need to know:')}${p('[Add arrival time, parking, what to bring.]')}${cta('View my tickets')}${sig()}`)),
  T('Events', 'Event day details', 'It\'s today! Here\'s what to know', shell(`${eyebrow('Today\'s the day')}${h1('See you very soon, {{name}}!')}${p('Today\'s the day! Doors open, timings, and everything you need is below:')}${p('[Add final details.]')}${sig()}`)),
  T('Events', 'Thank you for coming', 'Thank you for an amazing event', shell(`${eyebrow('Thank you')}${h1('{{name}}, you made it special.')}${p('Thank you for being part of it — the energy in the room was unforgettable. Photos and highlights are coming soon.')}${p('Missed it? Join us at the next one.')}${cta('See what\'s next')}${sig()}`)),
  T('Events', 'Showcase invite', 'Our end-of-term showcase', shell(`${eyebrow('Showcase')}${h1('Come and see what your children have built.')}${p('{{name}}, our end-of-term showcase is where the confidence, teamwork and skill all come together on stage. Bring the family.')}${ctaGold('Reserve seats')}${sig()}`)),
  T('Events', 'Community event', 'A free community event for everyone', shell(`${eyebrow('Free event')}${h1('On us: a free community celebration.')}${p('Hi {{name}} — we\'re hosting a free community event and everyone\'s welcome. Bring a friend, bring the family.')}${p('[Add details and date.]')}${cta('Let us know you\'re coming')}${sig()}`)),
  T('Events', 'Gala / fundraiser', 'Join us for a very special evening', shell(`${eyebrow('Special evening')}${h1('An evening of purpose and celebration.')}${p('{{name}}, join us for a special evening supporting the work of KADA with children across Birmingham.')}${p('[Add date, venue and ticket details.]')}${ctaGold('Get tickets')}${sig()}`)),
  T('Events', 'Post-event survey', 'How did we do?', shell(`${eyebrow('Quick question')}${h1('We\'d love your honest feedback, {{name}}.')}${p('Thanks for joining us. Two minutes of your thoughts helps us make the next event even better.')}${cta('Share feedback', 'mailto:bookings@kingsarkdance.com')}${sig()}`)),

  // ── Seasons & holidays ───────────────────────────────────────────
  T('Seasons', 'Christmas / end of year', 'Merry Christmas from the KADA family', shell(`${eyebrow('Season\'s greetings')}${h1('Wishing you a Christmas full of joy, {{name}}.')}${p('Thank you for being part of the KADA family this year. May your Christmas be full of love, faith and celebration.')}${p('We\'ll see you in the new year — rested and ready to dance.')}${sig()}`)),
  T('Seasons', 'New Year kick-off', 'New year, new confidence', shell(`${eyebrow('Happy New Year')}${h1('Let\'s make this their most confident year yet.')}${p('{{name}}, a new year means fresh energy, new routines and new goals. Classes restart soon — we\'d love to see your child there.')}${cta('Book for the new term')}${sig()}`)),
  T('Seasons', 'Easter holiday camp', 'Easter holiday dance camp', shell(`${eyebrow('Easter holidays')}${h1('Keep them moving this Easter, {{name}}.')}${p('Our Easter holiday sessions mix dance, games, creativity and faith-filled fun. Perfect while school\'s out.')}${ctaGold('Book Easter sessions')}${sig()}`)),
  T('Seasons', 'Summer intensive', 'Summer dance intensive — book now', shell(`${eyebrow('Summer intensive')}${h1('A summer they\'ll never forget.')}${p('{{name}}, our summer intensive is days of dance, friendship and performance — ending with a showcase for families.')}${p('Places are limited every year.')}${ctaGold('Reserve a place')}${sig()}`)),
  T('Seasons', 'Back to school', 'Back to school, back to dance', shell(`${eyebrow('September')}${h1('New term, fresh start, {{name}}.')}${p('As the school year begins, it\'s the perfect time to build a weekly rhythm of confidence and joy. Saturday classes are back.')}${cta('Book a Saturday class')}${sig()}`)),
  T('Seasons', 'Half-term club', 'Half-term dance club', shell(`${eyebrow('Half term')}${h1('Half-term plans? Sorted.')}${p('Hi {{name}} — our half-term club keeps children active, happy and creative while you work or rest.')}${ctaGold('Book half-term club')}${sig()}`)),
  T('Seasons', 'Black History Month (seasonal)', 'October is coming — book early', shell(`${eyebrow('Plan ahead')}${h1('Schools: October books up fast.')}${p('{{name}}, every year our Black History Month workshops sell out by early September. If your school wants a date, now is the moment.')}${ctaGold('Secure our date')}${sig()}`)),
  T('Seasons', 'Valentine\'s / kindness', 'A month of love and confidence', shell(`${eyebrow('February')}${h1('Building kind, confident hearts this month.')}${p('{{name}}, this month in class we\'re focusing on kindness, encouragement and lifting each other up — on and off the dance floor.')}${sig()}`)),

  // ── Community & nurture ──────────────────────────────────────────
  T('Community', 'Impact story', 'The moment everything changed', shell(`${eyebrow('Impact story')}${h1('A shy child found her voice.')}${p('{{name}}, this is why we do what we do. [Tell a short story of one child\'s transformation — 3–4 sentences.]')}${quote('She walked in hiding behind me. She danced out leading the group.', 'A KADA parent')}${cta('Read more stories')}${sig()}`)),
  T('Community', 'Volunteer call', 'Come and volunteer with KADA', shell(`${eyebrow('Volunteers')}${h1('Want to be part of the mission, {{name}}?')}${p('We\'re looking for helping hands — events, admin, chaperoning, media. An hour here and there changes children\'s lives.')}${cta('Register your interest', 'mailto:bookings@kingsarkdance.com')}${sig()}`)),
  T('Community', 'Partnership enquiry', 'Let\'s partner together', shell(`${eyebrow('Partnership')}${h1('Your organisation + KADA = bigger impact.')}${p('Hi {{name}} — we partner with organisations who care about young people: sponsorships, joint events, community programmes.')}${p('If that sounds like you, let\'s talk.')}${cta('Start the conversation', 'mailto:bookings@kingsarkdance.com')}${sig()}`)),
  T('Community', 'Testimonial request', 'Would you share your KADA story?', shell(`${eyebrow('Two minutes')}${h1('{{name}}, your words help other families find us.')}${p('If KADA has made a difference to your child or school, a short testimonial helps the next family take the leap.')}${cta('Share a few words', 'mailto:bookings@kingsarkdance.com')}${sig()}`)),
  T('Community', 'Referral thank-you', 'Thank you for spreading the word', shell(`${eyebrow('Thank you')}${h1('You referred a friend — that means everything.')}${p('{{name}}, thank you for telling another family about KADA. Word of mouth is how this movement grows.')}${p('As a thank-you, [add your referral reward here].')}${sig()}`)),
  T('Community', 'Birthday shoutout', 'Happy birthday! 🎂', shell(`${eyebrow('Happy birthday')}${h1('Happy birthday, {{name}}!')}${p('Wishing you a day full of joy, cake and — of course — dancing. From all of us at KADA.')}${sig()}`)),
  T('Community', 'Prayer / encouragement', 'A little encouragement for your week', shell(`${eyebrow('Encouragement')}${h1('A note of encouragement, {{name}}.')}${p('“Let your light shine before others.” This week, we\'re cheering for every child finding their confidence — and every parent making it possible.')}${sig()}`)),
  T('Community', 'Re-engagement (quiet list)', 'We\'d love to see you again', shell(`${eyebrow('We miss you')}${h1('{{name}}, it\'s been a while.')}${p('Life gets busy — we understand. If the timing is right again, we\'d love to welcome you back to class. Your place is always here.')}${cta('Come back to class')}${sig()}`)),
  T('Community', 'Newsletter (monthly)', 'Your KADA monthly round-up', shell(`${eyebrow('Monthly round-up')}${h1('Here\'s what happened this month at KADA.')}${p('Hi {{name}} — another month of confidence, culture and community. Here are the highlights:')}${p('[Add 2–3 short news items.]')}${divider}${p('Coming up next month: [add what\'s next].')}${cta('Visit the website')}${sig()}`)),
  T('Community', 'Photo / video share', 'This month\'s photos are in!', shell(`${eyebrow('Photos')}${h1('Look at these moments, {{name}}.')}${p('This month\'s class and workshop photos are ready — the joy on these faces says everything.')}${cta('View the gallery')}${sig()}`)),
]

export const TEMPLATE_CATEGORIES = [...new Set(TEMPLATES.map((t) => t.category))]
